services:
  - type: web
    name: eatsee-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
